/**
 * S5 — blocking: bounding the candidate search (matching-engine.md §3, ADR-033).
 *
 * This is the throughput answer, and it is an engineering answer rather than a
 * number. A naive Tier 2 compares every unmatched record against every other; at
 * the 100k-record benchmark that is ~5 billion comparisons and does not
 * complete. Candidates are therefore never generated by a full scan — four
 * in-memory indexes are built once per run, here, and every later stage draws
 * from them.
 *
 *   byStrongAnchor   (anchorKey::anchorValue) → ids   Tier 1, Tier 1.5, S8. O(1).
 *   byAnchorPrefix   first 6 chars of a strong anchor → ids   Tier 2 near-anchor (ADR-031)
 *   byDateAmount     (businessDate::amountBucket) → ids   Tier 2 primary candidate source
 *   byCounterparty   counterpartyKey (post-alias) → ids   Tier 2 secondary source
 *
 * Only STRUCTURED strong anchors go in `byStrongAnchor` / `byAnchorPrefix`
 * (`anchors.strongAnchors` already excludes description-extracted values —
 * identity may not rest on a regex hit, schema.md §3.1). Only RECONCILABLE rows
 * are indexed: excluded rows are already out of the denominator and must never
 * become a match candidate.
 *
 * Determinism (ADR-032): every id list is sorted by `compareCanonical`, so a
 * consumer walking a bucket sees the same order on every run regardless of Map
 * insertion order.
 */

import { compareCanonical } from '../../types/domain.js';
import type { BlockIndexes, NormalizedTransaction } from '../../types/engine.js';
import { strongAnchors } from './anchors.js';

/** ADR-033: `amount_bucket = floor(amount_paise / 100_000)` — ₹1,000 buckets. */
export const AMOUNT_BUCKET_PAISE = 100_000;

/** ADR-033 / §7.2: near-anchor candidates are bucketed by the first 6 characters. */
export const ANCHOR_PREFIX_LEN = 6;

const SEP = '::';

export function amountBucket(amountPaise: number): number {
  return Math.floor(Math.abs(amountPaise) / AMOUNT_BUCKET_PAISE);
}

function push(map: Map<string, string[]>, key: string, id: string): void {
  const list = map.get(key);
  if (list === undefined) map.set(key, [id]);
  else list.push(id);
}

/**
 * The key `byCounterparty` is built on. Post-alias `counterparty_key` when S7 has
 * run, `counterparty_norm` otherwise — so the index is correct whenever it is
 * built, and `rebuildCounterpartyIndex` refreshes just this map after S7.
 */
function counterpartyKeyOf(t: NormalizedTransaction): string | null {
  return t.counterpartyKey ?? t.counterpartyNorm;
}

export function buildBlockIndexes(pool: NormalizedTransaction[]): BlockIndexes {
  // Sort once, up front, so every bucket comes out canonically ordered without a
  // per-bucket sort.
  const rows = [...pool]
    .filter((t) => t.statusNorm === 'reconcilable')
    .sort(compareCanonical);

  const byStrongAnchor = new Map<string, string[]>();
  const byAnchorPrefix = new Map<string, string[]>();
  const byDateAmount = new Map<string, string[]>();
  const byCounterparty = new Map<string, string[]>();
  const byId = new Map<string, NormalizedTransaction>();

  for (const t of rows) {
    byId.set(t.id, t);

    for (const anchor of strongAnchors(t.referenceIds)) {
      push(byStrongAnchor, anchor.key + SEP + anchor.value, t.id);
      if (anchor.value.length >= ANCHOR_PREFIX_LEN) {
        push(byAnchorPrefix, anchor.value.slice(0, ANCHOR_PREFIX_LEN), t.id);
      }
    }

    push(byDateAmount, t.txnDate + SEP + amountBucket(t.amountPaise), t.id);

    const cp = counterpartyKeyOf(t);
    if (cp !== null) push(byCounterparty, cp, t.id);
  }

  return { byStrongAnchor, byAnchorPrefix, byDateAmount, byCounterparty, byId };
}

/**
 * Rebuild only `byCounterparty` from the current pool — cheap, and the honest way
 * to give Tier 2 the post-alias `counterparty_key` when S7 populated it after S5
 * already ran (matching-engine.md §3 note, §7 "secondary effect"). The pool rows
 * must be the same objects (or updated copies) S7 produced.
 */
export function rebuildCounterpartyIndex(blocks: BlockIndexes, pool: NormalizedTransaction[]): void {
  const rebuilt = new Map<string, string[]>();
  for (const t of [...pool].filter((x) => x.statusNorm === 'reconcilable').sort(compareCanonical)) {
    const cp = counterpartyKeyOf(t);
    if (cp !== null) push(rebuilt, cp, t.id);
    blocks.byId.set(t.id, t);
  }
  blocks.byCounterparty = rebuilt;
}

/**
 * Every unordered cross-source pair that shares at least one structured strong
 * anchor, each pair emitted exactly once, in a deterministic order. This is the
 * candidate stream S6, S7 and S8 all consume.
 *
 * Post-S4 a strong anchor value is unique within a source (S4 excluded the
 * copies), so a bucket holds at most one row per source and this is near-linear.
 */
export function strongAnchorPairs(
  blocks: BlockIndexes,
): { a: NormalizedTransaction; b: NormalizedTransaction; slot: string }[] {
  const out: { a: NormalizedTransaction; b: NormalizedTransaction; slot: string }[] = [];
  const seen = new Set<string>();

  for (const slot of [...blocks.byStrongAnchor.keys()].sort()) {
    const ids = blocks.byStrongAnchor.get(slot)!;
    for (let i = 0; i < ids.length; i += 1) {
      for (let j = i + 1; j < ids.length; j += 1) {
        const a = blocks.byId.get(ids[i]!)!;
        const b = blocks.byId.get(ids[j]!)!;
        if (a.sourceSystem === b.sourceSystem) continue; // same-source share ⇒ S4's job, not matching's
        const pairKey = compareCanonical(a, b) <= 0 ? `${a.id}|${b.id}` : `${b.id}|${a.id}`;
        if (seen.has(pairKey)) continue;
        seen.add(pairKey);
        out.push(compareCanonical(a, b) <= 0 ? { a, b, slot } : { a: b, b: a, slot });
      }
    }
  }
  return out;
}
